using System.Collections.Generic;

namespace Server.Systems.MahaonCreatures;

/// <summary>Отдельная таблица, ключ - имя C#-класса (то самое, что реально хранится в
/// SpawnerEntry.SpawnedName для поиска типа рефлексией — MahaonCreatureNameTable ключуется
/// по DefaultName ("a skeleton"), это другая строка, чем имя класса ("Skeleton")).
/// Показывается ТОЛЬКО косметически рядом с техническим именем в гампе спаунера —
/// само SpawnedName не трогается, иначе сломался бы AssemblyHandler.FindTypeByName.</summary>
public static class MahaonCreatureNameTableBySpawnerType
{
    public static readonly Dictionary<string, string> Translations = new()
    {
        ["Skeleton"] = "скелет",
        ["Zombie"] = "зомби",
        ["Ghoul"] = "упырь",
        ["Mummy"] = "мумия",
        ["Lich"] = "лич",
        ["LichLord"] = "лорд-лич",
        ["Wraith"] = "призрак",
        ["Spectre"] = "спектр",
        ["Shade"] = "тень",
        ["HeadlessOne"] = "безголовый",
        ["Bogling"] = "болотник",
        ["BogThing"] = "болотное существо",
        ["Ratman"] = "крысолюд",
        ["RatmanMage"] = "крысолюд-маг",
        ["RatmanArcher"] = "крысолюд-лучник",
        ["Orc"] = "орк",
        ["OrcBomber"] = "орк-подрывник",
        ["OrcBrute"] = "орк-громила",
        ["OrcCaptain"] = "орк-капитан",
        ["OrcishMage"] = "орк-маг",
        ["OrcishLord"] = "орк-лорд",
        ["Gargoyle"] = "гаргулья",
        ["GargoyleDestroyer"] = "гаргулья-разрушитель",
        ["GargoyleEnforcer"] = "гаргулья-каратель",
        ["StoneGargoyle"] = "каменная гаргулья",
        ["Gazer"] = "глазастик",
        ["ElderGazer"] = "старший глазастик",
        ["HellHound"] = "адский пёс",
        ["EarthElemental"] = "элементаль земли",
        ["AirElemental"] = "элементаль воздуха",
        ["FireElemental"] = "элементаль огня",
        ["WaterElemental"] = "элементаль воды",
        ["BloodElemental"] = "элементаль крови",
        ["PoisonElemental"] = "элементаль яда",
        ["SnowElemental"] = "элементаль снега",
        ["AgapiteElemental"] = "элементаль агапита",
        ["BronzeElemental"] = "элементаль бронзы",
        ["CopperElemental"] = "элементаль меди",
        ["DreadSpider"] = "жуткий паук",
        ["GiantSpider"] = "гигантский паук",
        ["GiantBlackWidow"] = "гигантская чёрная вдова",
        ["GiantToad"] = "гигантская жаба",
        ["HordeMinion"] = "прислужник орды",
        ["Ogre"] = "огр",
        ["OgreLord"] = "огр-лорд",
        ["Troll"] = "тролль",
        ["Ettin"] = "эттин",
        ["Titan"] = "титан",
        ["Cyclops"] = "циклоп",
        ["Daemon"] = "демон",
        ["Succubus"] = "суккуб",
        ["Imp"] = "имп",
        ["Balron"] = "балрон",
        ["LavaLizard"] = "лавовая ящерица",
        ["LavaSerpent"] = "лавовый змей",
        ["SwampDragon"] = "болотный дракон",
        ["Drake"] = "дракончик",
        ["Dragon"] = "дракон",
        ["AncientWyrm"] = "древний змей",
        ["SerpentineDragon"] = "змеиный дракон",
        ["ShadowWyrm"] = "теневой змей",
        ["WhiteWyrm"] = "белый змей",
        ["Rat"] = "крыса",
        ["GiantRat"] = "гигантская крыса",
        ["DireWolf"] = "лютый волк",
        ["TimberWolf"] = "лесной волк",
        ["Wolf"] = "волк",
        ["Bear"] = "медведь",
        ["GrizzlyBear"] = "гризли",
        ["PolarBear"] = "белый медведь",
        ["BlackBear"] = "чёрный медведь",
        ["Panther"] = "пантера",
        ["Cougar"] = "кугуар",
        ["Walrus"] = "морж",
        ["Horse"] = "лошадь",
        ["Nightmare"] = "ночной кошмар",
        ["Unicorn"] = "единорог",
        ["Kirin"] = "цилинь",
        ["Llama"] = "лама",
        ["Mongbat"] = "монгбэт",
        ["StrongMongbat"] = "сильный монгбэт",
        ["Harpy"] = "гарпия",
        ["StoneHarpy"] = "каменная гарпия",
        ["Scorpion"] = "скорпион",
        ["TerathanAvenger"] = "теретан-мститель",
        ["TerathanDrone"] = "теретан-трутень",
        ["TerathanMatriarch"] = "теретан-матриарх",
        ["TerathanWarrior"] = "теретан-воин",
        ["SolenWorker"] = "солен-рабочий",
        ["SolenWarrior"] = "солен-воин",
        ["SilverSerpent"] = "серебряный змей",
        ["SeaSerpent"] = "морской змей",
        ["DeepSeaSerpent"] = "глубоководный змей",
        ["Corpser"] = "трупосбор",
        ["BakeKitsune"] = "бакэ-кицунэ",
        ["FanDancer"] = "танцовщица с веерами",
        ["Lizardman"] = "ящеролюд",
        ["LizardmanShaman"] = "ящеролюд-шаман",
        ["Leviathan"] = "левиафан",
        ["Reaper"] = "жнец",
        ["DreadHorn"] = "жуткий рог",
        ["Slime"] = "слизь",

        // Партия 2
        ["Cow"] = "корова",
        ["Pig"] = "свинья",
        ["Sheep"] = "овца",
        ["Chicken"] = "курица",
        ["Goat"] = "коза",
        ["Eagle"] = "орёл",
        ["Alligator"] = "аллигатор",
        ["FrenziedOstard"] = "бешеный остард",
        ["RidableLlama"] = "верховая лама",
        ["GreatHart"] = "большой олень",
        ["Rabbit"] = "кролик",
        ["Squirrel"] = "белка",
        ["PackHorse"] = "вьючная лошадь",
        ["GreyWolf"] = "серый волк",
        ["WhiteWolf"] = "белый волк",
        ["GiantSerpent"] = "гигантская змея",
        ["SandVortex"] = "песчаный вихрь",
        ["FrostSpider"] = "морозный паук",
        ["AntLion"] = "муравьиный лев",
        ["IceFiend"] = "ледяной демон",
        ["IceSnake"] = "ледяная змея",
        ["IceSerpent"] = "гигантский ледяной змей",
        ["PredatorHellCat"] = "адская кошка",
        ["Wisp"] = "болотный огонёк",
        ["CrystalElemental"] = "кристальный элементаль",
        ["Yamandon"] = "ямандон",
        ["SkeletalDragon"] = "скелетный дракон",
        ["SkeletalKnight"] = "скелет-рыцарь",
        ["BoneKnight"] = "костяной рыцарь",
        ["BoneMagi"] = "костяной маг",
        ["OphidianMatriarch"] = "офидианка-матриарх",

        // Партия 3
        ["Barracoon"] = "Барракун",
        ["LordOaks"] = "Лорд Оукс",
        ["Semidar"] = "Семидар",
        ["Mephitis"] = "Мефитис",
        ["Serado"] = "Серадо",
        ["Rikktor"] = "Риктор",
        ["Neira"] = "Нейра",
        ["FleshRenderer"] = "плоторез",
        ["ExodusMinion"] = "прислужник Исхода",
        ["PatchworkSkeleton"] = "лоскутный скелет",
        ["Efreet"] = "ифрит",
        ["DeathWatchBeetle"] = "жук смертного часа",
        ["FireBeetle"] = "огненный жук",
        ["GreaterMongbat"] = "старший монгбэт",
        ["Dolphin"] = "дельфин",
        ["SavageRidgeback"] = "дикарский гребнеспин",
        ["WhippingVine"] = "хлещущая лоза",
        ["ArcticOgreLord"] = "арктический огр-лорд",
        ["SkeletalMage"] = "скелет-маг",
        ["VampireBat"] = "вампирская летучая мышь",

        // Партия 4
        ["Satyr"] = "сатир",
        ["MinotaurCaptain"] = "минотавр-капитан",
        ["MinotaurScout"] = "минотавр-разведчик",
        ["Minotaur"] = "минотавр",
        ["GreaterDragon"] = "великий дракон",
        ["Betrayer"] = "предатель",
        ["Beetle"] = "гигантский жук",
        ["Kraken"] = "кракен",
        ["StoneSlith"] = "каменный слит",
        ["Gibberling"] = "бормотун",
        ["Changeling"] = "оборотень-подменыш",
        ["MoundOfMaggots"] = "куча личинок",
        ["FetidEssence"] = "зловонная эссенция",
        ["Devourer"] = "пожиратель душ",
        ["ArcaneDaemon"] = "тайный демон",
        ["AcidElemental"] = "элементаль кислоты",
        ["RagingGrizzlyBear"] = "яростный гризли",
        ["RedSolenWorker"] = "красный солен-рабочий",
        ["RedSolenWarrior"] = "красный солен-воин",
        ["RedSolenQueen"] = "красный солен-королева",
        ["BlackSolenWorker"] = "чёрный солен-рабочий",
        ["BlackSolenWarrior"] = "чёрный солен-воин",
        ["BlackSolenQueen"] = "чёрный солен-королева",
        ["EnslavedGargoyle"] = "порабощённая гаргулья",
        ["Golem"] = "голем",
        ["EnergyVortex"] = "энергетический вихрь",

        // Партия 5
        ["Cat"] = "кошка",
        ["JukaLord"] = "джука-лорд",
        ["JukaMage"] = "джука-маг",
        ["JukaWarrior"] = "джука-воин",
        ["Meraktus"] = "Мерактус",
        ["ChaosDragoon"] = "драгун хаоса",
        ["ChaosDragoonElite"] = "элитный драгун хаоса",
        ["DarkGuardian"] = "тёмный страж",
        ["SilverSteed"] = "серебряный скакун",
        ["RedDeath"] = "Красная Смерть",
        ["BullFrog"] = "бык-лягушка",
        ["SwampTentacle"] = "болотное щупальце",
        ["AbysmalHorror"] = "бездонный ужас",
        ["TsukiWolf"] = "цуки-волк"
    };

    public static bool TryGet(string className, out string russianName) =>
        Translations.TryGetValue(className, out russianName);
}
