using System.Collections.Generic;

namespace Server.Systems.MahaonCreatures;

/// <summary>Русские названия существ — ключ - настоящее английское DefaultName (не имя
/// C#-класса), значение - русский перевод. Применяется один раз при создании существа
/// (см. хук в конце основного конструктора BaseCreature), не трогает саму строку
/// DefaultName в файлах существ — 671 файл, править каждый по отдельности честно не
/// вариант.
///
/// НАЧАЛЬНЫЙ НАБОР, не полное покрытие всех существ — самые частые/знаковые monsters на
/// первый проход. Остальные добавляются сюда по мере необходимости, без изменения
/// механизма применения.</summary>
public static class MahaonCreatureNameTable
{
    public static readonly Dictionary<string, string> Translations = new()
    {
        ["a skeleton"] = "скелет",
        ["a zombie"] = "зомби",
        ["a ghoul"] = "упырь",
        ["a mummy"] = "мумия",
        ["a lich"] = "лич",
        ["a lich lord"] = "лорд-лич",
        ["a wraith"] = "призрак",
        ["a spectre"] = "спектр",
        ["a shade"] = "тень",
        ["a headless one"] = "безголовый",
        ["a bogling"] = "болотник",
        ["a bog thing"] = "болотное существо",
        ["a ratman"] = "крысолюд",
        ["a ratman mage"] = "крысолюд-маг",
        ["a ratman archer"] = "крысолюд-лучник",
        ["an orc"] = "орк",
        ["an orc bomber"] = "орк-подрывник",
        ["an orc brute"] = "орк-громила",
        ["an orc captain"] = "орк-капитан",
        ["an orcish mage"] = "орк-маг",
        ["an orcish lord"] = "орк-лорд",
        ["a gargoyle"] = "гаргулья",
        ["a gargoyle destroyer"] = "гаргулья-разрушитель",
        ["a gargoyle enforcer"] = "гаргулья-каратель",
        ["a stone gargoyle"] = "каменная гаргулья",
        ["a gazer"] = "глазастик",
        ["an elder gazer"] = "старший глазастик",
        ["a hell hound"] = "адский пёс",
        ["an earth elemental"] = "элементаль земли",
        ["an air elemental"] = "элементаль воздуха",
        ["a fire elemental"] = "элементаль огня",
        ["a water elemental"] = "элементаль воды",
        ["a blood elemental"] = "элементаль крови",
        ["a poison elemental"] = "элементаль яда",
        ["a snow elemental"] = "элементаль снега",
        ["an agapite elemental"] = "элементаль агапита",
        ["a bronze elemental"] = "элементаль бронзы",
        ["a copper elemental"] = "элементаль меди",
        ["a dread spider"] = "жуткий паук",
        ["a giant spider"] = "гигантский паук",
        ["a giant black widow"] = "гигантская чёрная вдова",
        ["a giant toad"] = "гигантская жаба",
        ["a horde minion"] = "прислужник орды",
        ["an ogre"] = "огр",
        ["an ogre lord"] = "огр-лорд",
        ["a troll"] = "тролль",
        ["an ettin"] = "эттин",
        ["a titan"] = "титан",
        ["a cyclops"] = "циклоп",
        ["a daemon"] = "демон",
        ["a succubus"] = "суккуб",
        ["an imp"] = "имп",
        ["a balron"] = "балрон",
        ["a lava lizard"] = "лавовая ящерица",
        ["a lava serpent"] = "лавовый змей",
        ["a swamp dragon"] = "болотный дракон",
        ["a drake"] = "дракончик",
        ["a dragon"] = "дракон",
        ["an ancient wyrm"] = "древний змей",
        ["a serpentine dragon"] = "змеиный дракон",
        ["a shadow wyrm"] = "теневой змей",
        ["a white wyrm"] = "белый змей",
        ["a rat"] = "крыса",
        ["a giant rat"] = "гигантская крыса",
        ["a dire wolf"] = "лютый волк",
        ["a timber wolf"] = "лесной волк",
        ["a wolf"] = "волк",
        ["a bear"] = "медведь",
        ["a grizzly bear"] = "гризли",
        ["a polar bear"] = "белый медведь",
        ["a black bear"] = "чёрный медведь",
        ["a panther"] = "пантера",
        ["a cougar"] = "кугуар",
        ["a walrus"] = "морж",
        ["a horse"] = "лошадь",
        ["a nightmare"] = "ночной кошмар",
        ["a unicorn"] = "единорог",
        ["a kirin"] = "цилинь",
        ["a ki-rin"] = "цилинь",
        ["a llama"] = "лама",
        ["a mongbat"] = "монгбэт",
        ["a strong mongbat"] = "сильный монгбэт",
        ["a harpy"] = "гарпия",
        ["a stone harpy"] = "каменная гарпия",
        ["a scorpion"] = "скорпион",
        ["a terathan avenger"] = "теретан-мститель",
        ["a terathan drone"] = "теретан-трутень",
        ["a terathan matriarch"] = "теретан-матриарх",
        ["a terathan warrior"] = "теретан-воин",
        ["a solen infiltrator queen"] = "солен-инфильтратор-королева",
        ["a solen worker"] = "солен-рабочий",
        ["a solen warrior"] = "солен-воин",
        ["a silver serpent"] = "серебряный змей",
        ["a sea serpent"] = "морской змей",
        ["a deep sea serpent"] = "глубоководный змей",
        ["a corpser"] = "трупосбор",
        ["a bake kitsune"] = "бакэ-кицунэ",
        ["a fan dancer"] = "танцовщица с веерами",
        ["a lizardman"] = "ящеролюд",
        ["a lizardman shaman"] = "ящеролюд-шаман",
        ["a leviathan"] = "левиафан",
        ["a reaper"] = "жнец",
        ["a dread horn"] = "жуткий рог",
        ["a slime"] = "слизь",

        // Партия 2 — фермерские, лесные, ледяные, скелетные варианты
        ["a cow"] = "корова",
        ["a pig"] = "свинья",
        ["a sheep"] = "овца",
        ["a chicken"] = "курица",
        ["a goat"] = "коза",
        ["an eagle"] = "орёл",
        ["an alligator"] = "аллигатор",
        ["a frenzied ostard"] = "бешеный остард",
        ["a ridable llama"] = "верховая лама",
        ["a great hart"] = "большой олень",
        ["a rabbit"] = "кролик",
        ["a squirrell"] = "белка", // да, опечатка в самой ванили ("squirrell") — ключ должен совпасть точно
        ["a pack horse"] = "вьючная лошадь",
        ["a grey wolf"] = "серый волк",
        ["a white wolf"] = "белый волк",
        ["a giant snake"] = "гигантская змея",
        ["a sand vortex"] = "песчаный вихрь",
        ["a frost spider"] = "морозный паук",
        ["an ant lion"] = "муравьиный лев",
        ["an ice fiend"] = "ледяной демон",
        ["an ice snake"] = "ледяная змея",
        ["a giant ice serpent"] = "гигантский ледяной змей",
        ["a hell cat"] = "адская кошка",
        ["a wisp"] = "болотный огонёк",
        ["a crystal elemental"] = "кристальный элементаль",
        ["a yamandon"] = "ямандон",
        ["a skeletal dragon"] = "скелетный дракон",
        ["a skeletal knight"] = "скелет-рыцарь",
        ["a bone knight"] = "костяной рыцарь",
        ["a bone mage"] = "костяной маг",
        ["an ophidian matriarch"] = "офидианка-матриарх",

        // Партия 3 — боссы чемпионских спавнов (транслитерация имён) и дополнительные существа
        ["Barracoon"] = "Барракун",
        ["Lord Oaks"] = "Лорд Оукс",
        ["Semidar"] = "Семидар",
        ["Mephitis"] = "Мефитис",
        ["Serado"] = "Серадо",
        ["Rikktor"] = "Риктор",
        ["Neira"] = "Нейра",
        ["a fleshrenderer"] = "плоторез",
        ["an exodus minion"] = "прислужник Исхода",
        ["a patchwork skeleton"] = "лоскутный скелет",
        ["an efreet"] = "ифрит",
        ["a deathwatch beetle"] = "жук смертного часа",
        ["a fire beetle"] = "огненный жук",
        ["a greater mongbat"] = "старший монгбэт",
        ["a dolphin"] = "дельфин",
        ["a savage ridgeback"] = "дикарский гребнеспин",
        ["a whipping vine"] = "хлещущая лоза",
        ["an arctic ogre lord"] = "арктический огр-лорд",
        ["a skeletal mage"] = "скелет-маг",
        ["a vampire bat"] = "вампирская летучая мышь",

        // Партия 4 — минотавры, солены, элементали, големы, разное
        ["a satyr"] = "сатир",
        ["a minotaur captain"] = "минотавр-капитан",
        ["a minotaur scout"] = "минотавр-разведчик",
        ["a minotaur"] = "минотавр",
        ["a greater dragon"] = "великий дракон",
        ["a betrayer"] = "предатель",
        ["a giant beetle"] = "гигантский жук",
        ["a kraken"] = "кракен",
        ["a stone slith"] = "каменный слит",
        ["a gibberling"] = "бормотун",
        ["a changeling"] = "оборотень-подменыш",
        ["a mound of maggots"] = "куча личинок",
        ["a fetid essence"] = "зловонная эссенция",
        ["a devourer of souls"] = "пожиратель душ",
        ["an arcane daemon"] = "тайный демон",
        ["an acid elemental"] = "элементаль кислоты",
        ["a raging grizzly bear"] = "яростный гризли",
        ["a red solen worker"] = "красный солен-рабочий",
        ["a red solen warrior"] = "красный солен-воин",
        ["a red solen queen"] = "красный солен-королева",
        ["a black solen worker"] = "чёрный солен-рабочий",
        ["a black solen warrior"] = "чёрный солен-воин",
        ["a black solen queen"] = "чёрный солен-королева",
        ["an enslaved gargoyle"] = "порабощённая гаргулья",
        ["a golem"] = "голем",
        ["an energy vortex"] = "энергетический вихрь",

        // Партия 5 — Джука, кошки, лягушки, разное
        ["a cat"] = "кошка",
        ["a juka lord"] = "джука-лорд",
        ["a juka mage"] = "джука-маг",
        ["a juka warrior"] = "джука-воин",
        ["Meraktus"] = "Мерактус",
        ["a chaos dragoon"] = "драгун хаоса",
        ["a chaos dragoon elite"] = "элитный драгун хаоса",
        ["a dark guardian"] = "тёмный страж",
        ["a silver steed"] = "серебряный скакун",
        ["Red Death"] = "Красная Смерть",
        ["a bull frog"] = "бык-лягушка",
        ["a swamp tentacle"] = "болотное щупальце",
        ["an abysmal horror"] = "бездонный ужас",
        ["a tsuki wolf"] = "цуки-волк",

        // Партия 6
        ["Abscess"] = "Абсцесс",
        ["Chiikkaha the Toothed"] = "Чиккаха Зубастая",
        ["Coil"] = "Кольцо",
        ["Crystal Lattice Seeker"] = "Кристальный решётчатый искатель",
        ["Gnaw"] = "Грызло",
        ["Grobu"] = "Гробу",
        ["Guile"] = "Коварство",
        ["Ilhenir"] = "Ильхенир",
        ["Irk"] = "Ирк",
        ["Lady Jennifyr"] = "Леди Дженнифир",
        ["Lady Lissith"] = "Леди Лиссит",
        ["Lady Marai"] = "Леди Марай",
        ["Lady Sabrix"] = "Леди Сабрикс",
        ["Lurg"] = "Лург",
        ["Malefic"] = "Малефик",
        ["Master Jonath"] = "Мастер Джонат",
        ["Master Mikael"] = "Мастер Микаэль",
        ["Master Theophilus"] = "Мастер Теофилус",
        ["Miasma"] = "Миазм",
        ["Moug-Guur"] = "Мауг-Гуур",
        ["Putrefier"] = "Разложитель",
        ["Pyre"] = "Костёр",
        ["Rend"] = "Разрыв",
        ["Saliva"] = "Слюна",
        ["Silk"] = "Шёлк",
        ["Silvani"] = "Сильвани",
        ["Sir Patrick"] = "Сэр Патрик",
        ["Spite"] = "Злоба",
        ["Swoop"] = "Налёт",
        ["Szavetra"] = "Сзаветра",
        ["Tangle"] = "Путаница",
        ["Thrasher"] = "Молотильщик",
        ["Tormented Minotaur"] = "Измученный минотавр",
        ["Twaulo"] = "Тваулo",
        ["Virulent"] = "Ядовитый",
        ["Zealot of Khaldun"] = "Фанатик Халдуна",
        ["a Protector"] = "защитник",
        ["a Rai-Ju"] = "рай-дзю",
        ["a Revenant Lion"] = "лев-ревенант",
        ["a Servant of Semidar"] = "служитель Семидар",

        // Партия 7 — весь оставшийся список
        ["a black solen infiltrator"] = "чёрный солен-лазутчик",
        ["a blackthorn juggernaut"] = "джаггернаут Блэкторна",
        ["a blade spirit"] = "клинковый дух",
        ["a boar"] = "кабан",
        ["a bogle"] = "боглин",
        ["a bone demon"] = "костяной демон",
        ["a brown bear"] = "бурый медведь",
        ["a bull"] = "бык",
        ["a chaos daemon"] = "демон хаоса",
        ["a corporeal brume"] = "телесная дымка",
        ["a corrosive slime"] = "едкая слизь",
        ["a corrupted soul"] = "порочная душа",
        ["a crane"] = "журавль",
        ["a crystal daemon"] = "кристальный демон",
        ["a crystal sea serpent"] = "кристальный морской змей",
        ["a crystal vortex"] = "кристальный вихрь",
        ["a crystal wisp"] = "кристальный огонёк",
        ["a cu sidhe"] = "ку ши",
        ["a cyclopean warrior"] = "циклопический воин",
        ["a dark wolf"] = "тёмный волк",
        ["a death adder"] = "смертельная гадюка",
        ["a deathwatch beetle hatchling"] = "детёныш жука смертного часа",
        ["a desert ostard"] = "пустынный остард",
        ["a dog"] = "собака",
        ["a doppleganger"] = "двойник",
        ["a dryad"] = "дриада",
        ["a dull copper elemental"] = "элементаль тусклой меди",
        ["a feral treefellow"] = "дикий древень",
        ["a ferret"] = "хорёк",
        ["a fire steed"] = "огненный скакун",
        ["a flesh golem"] = "плотяной голем",
        ["a forest ostard"] = "лесной остард",
        ["a frost ooze"] = "морозная слизь",
        ["a frost troll"] = "морозный тролль",
        ["a gaman"] = "гаман",
        ["a gazer larva"] = "личинка глазастика",
        ["a giant black wide"] = "гигантская чёрная вдова",
        ["a golden elemental"] = "золотой элементаль",
        ["a gore fiend"] = "кровавый демон",
        ["a gorilla"] = "горилла",
        ["a grizzled mare"] = "поседевшая кобыла",
        ["a hellsteed"] = "адский скакун",
        ["a hind"] = "лань",
        ["a hiryu"] = "хирю",
        ["a hydra"] = "гидра",
        ["a interred grizzle"] = "погребённый гризли",
        ["a jack rabbit"] = "заяц",
        ["a jwilson"] = "джей-уилсон",
        ["a kappa"] = "каппа",
        ["a kaze kemono"] = "кадзэ-кемоно",
        ["a lady of the snow"] = "снежная леди",
        ["a lava snake"] = "лавовая змея",
        ["a lesser hiryu"] = "малый хирю",
        ["a mantra effervescence"] = "мантра шипения",
        ["a meer captain"] = "миир-капитан",
        ["a meer eternal"] = "вечный миир",
        ["a meer mage"] = "миир-маг",
        ["a meer warrior"] = "миир-воин",
        ["a moloch"] = "молох",
        ["a mountain goat"] = "горный козёл",
        ["a mysterious rabbit hole"] = "загадочная кроличья нора",
        ["a pack llama"] = "вьючная лама",
        ["a parrot"] = "попугай",
        ["a pestilent bandage"] = "моровая повязка",
        ["a phoenix"] = "феникс",
        ["a plague beast lord"] = "лорд чумного зверя",
        ["a plague beast"] = "чумной зверь",
        ["a plague spawn"] = "чумной выродок",
        ["a quagmire"] = "трясина",
        ["a raptor"] = "раптор",
        ["a ravager"] = "разоритель",
        ["a red solen infiltrator"] = "красный солен-лазутчик",
        ["a reptalon"] = "рептилон",
        ["a restless soul"] = "неупокоенная душа",
        ["a revenant"] = "ревенант",
        ["a ridgeback"] = "гребнеспин",
        ["a ronin"] = "ронин",
        ["a rotting corpse"] = "гниющий труп",
        ["a rune beetle"] = "рунный жук",
        ["a sea horse"] = "морской конёк",
        ["a sewer rat"] = "канализационная крыса",
        ["a shadow fiend"] = "теневой демон",
        ["a shadow iron elemental"] = "элементаль тёмного железа",
        ["a shadow wisp"] = "теневой огонёк",
        ["a skeletal steed"] = "скелетный скакун",
        ["a skittering hopper"] = "суетливый попрыгун",
        ["a slith"] = "слит",
        ["a snake"] = "змея",
        ["a snow leopard"] = "снежный барс",
        ["a spectral armour"] = "призрачная броня",
        ["a spectral spellbinder"] = "призрачный чароплёт",
        ["a toxic slith"] = "ядовитый слит",
        ["a treefellow"] = "древень",
        ["a troglodyte"] = "троглодит",
        ["a tropical bird"] = "тропическая птица",
        ["a valorite elemental"] = "элементаль валорита",
        ["a verite elemental"] = "элементаль верита",
        ["a vorpal bunny"] = "смертоносный кролик",
        ["a wailing banshee"] = "воющая банши",
        ["a wanderer of the void"] = "странник пустоты",
        ["a war horse"] = "боевой конь",
        ["a wyvern"] = "виверна",
        ["a yomotsu elder"] = "старейшина ёмоцу",
        ["a yomotsu priest"] = "жрец ёмоцу",
        ["a yomotsu warrior"] = "воин ёмоцу",
        ["an animated weapon"] = "одушевлённое оружие",
        ["an elite ninja"] = "элитный ниндзя",
        ["an enslaved satyr"] = "порабощённый сатир",
        ["an exodus overseer"] = "надзиратель Исхода",
        ["an ice elemental"] = "элементаль льда",
        ["an insane dryad"] = "безумная дриада",
        ["an oni"] = "они",
        ["an unfrozen mummy"] = "размороженная мумия",
        ["tentacles of the harrower"] = "щупальца Разорителя",
        ["the harrower"] = "Разоритель"
    };

    public static bool TryGet(string englishDefaultName, out string russianName)
    {
        // Dictionary.TryGetValue(null, ...) реально бросает ArgumentNullException для
        // string-ключа (проверено на живом краше) — защита прямо тут, чтобы больше
        // никогда не приходилось помнить проверять на null на каждом месте вызова.
        if (englishDefaultName == null)
        {
            russianName = null;
            return false;
        }

        return Translations.TryGetValue(englishDefaultName, out russianName);
    }
}
